// ข้อมูลสระภาษาอังกฤษทั้งหมด — หัวใจของเกม
// group = หมวดย่อยตามตระกูลเสียง (เล่นทีละหมวดจะสั้น เล่นจบไว)
// spellWord / spellAnswer ใช้สำหรับโหมดฝึกสะกดคำ (spellAnswer ต้องเป็นส่วนหนึ่งของ spellWord)
// หมายเหตุ: เสียงที่ใส่คือ "เสียงหลัก" — บางรูปมีหลายเสียง (ระบุไว้ใน hint)
const VOWELS = [
  // ══════════ หมวด 1: Magic e (สระ + พยัญชนะ + e เงียบ) ══════════
  { id: "a-e", group: "magic-e", display: "a_e", ipa: "/eɪ/", thai: "เอ",
    examples: ["game", "cake", "name"], sentence: "I play a {game}.",
    hint: "e เงียบ แต่ทำให้ a ออกเสียง 'เอ'", spellWord: "game", spellAnswer: "a" },
  { id: "i-e", group: "magic-e", display: "i_e", ipa: "/aɪ/", thai: "ไอ",
    examples: ["bike", "time", "nice"], sentence: "I ride my {bike}.",
    hint: "e เงียบ แต่ทำให้ i ออกเสียง 'อาย'", spellWord: "bike", spellAnswer: "i" },
  { id: "o-e", group: "magic-e", display: "o_e", ipa: "/oʊ/", thai: "โอ",
    examples: ["home", "nose", "bone"], sentence: "I go {home}.",
    hint: "e เงียบ แต่ทำให้ o ออกเสียง 'โอ'", spellWord: "home", spellAnswer: "o" },
  { id: "u-e", group: "magic-e", display: "u_e", ipa: "/juː/", thai: "ยู",
    examples: ["cute", "cube", "use"], sentence: "The cat is {cute}.",
    hint: "e เงียบ ทำให้ u ออก 'ยู' (บางคำ 'อู' เช่น rule, June)", spellWord: "cute", spellAnswer: "u" },
  { id: "e-e", group: "magic-e", display: "e_e", ipa: "/iː/", thai: "อี",
    examples: ["these", "theme", "Pete"], sentence: "I like {these}.",
    hint: "e เงียบ แต่ทำให้ e ออกเสียง 'อี'", spellWord: "these", spellAnswer: "e" },

  // ══════════ หมวด 2: เสียง เอ /eɪ/ ══════════
  { id: "ai", group: "long-a", display: "ai", ipa: "/eɪ/", thai: "เอ",
    examples: ["rain", "train", "wait"], sentence: "Wait for the {train}.",
    hint: "ai ออก 'เอ' (มักอยู่กลางคำ)", spellWord: "train", spellAnswer: "ai" },
  { id: "ay", group: "long-a", display: "ay", ipa: "/eɪ/", thai: "เอ",
    examples: ["day", "play", "say"], sentence: "Let's {play} today.",
    hint: "ay ออก 'เอ' (มักอยู่ท้ายคำ)", spellWord: "play", spellAnswer: "ay" },
  { id: "ey-ay", group: "long-a", display: "ey", ipa: "/eɪ/", thai: "เอ",
    examples: ["they", "grey", "obey"], sentence: "{They} are happy.",
    hint: "ey บางคำออก 'เอ' เช่น they, grey", spellWord: "they", spellAnswer: "ey" },
  { id: "eigh", group: "long-a", display: "eigh", ipa: "/eɪ/", thai: "เอ",
    examples: ["eight", "weigh", "sleigh"], sentence: "I have {eight} pens.",
    hint: "eigh ออก 'เอ' (gh เงียบ)", spellWord: "eight", spellAnswer: "eigh" },
  { id: "ei", group: "long-a", display: "ei", ipa: "/eɪ/", thai: "เอ",
    examples: ["vein", "rein", "veil"], sentence: "A {vein} in the arm.",
    hint: "ei บางคำออก 'เอ' (บางคำ 'อี' เช่น receive)", spellWord: "vein", spellAnswer: "ei" },

  // ══════════ หมวด 3: เสียง อี /iː/ ══════════
  { id: "ee", group: "long-e", display: "ee", ipa: "/iː/", thai: "อี",
    examples: ["see", "tree", "bee"], sentence: "I {see} a tree.",
    hint: "ee เสียงยาว 'อี'", spellWord: "see", spellAnswer: "ee" },
  { id: "ea", group: "long-e", display: "ea", ipa: "/iː/", thai: "อี",
    examples: ["sea", "tea", "eat"], sentence: "Let's {eat} now.",
    hint: "ea ส่วนใหญ่ออก 'อี' (บางคำ 'เอะ' เช่น bread, head)", spellWord: "sea", spellAnswer: "ea" },
  { id: "ey-ee", group: "long-e", display: "ey", ipa: "/iː/", thai: "อี",
    examples: ["key", "money", "honey"], sentence: "Where is the {key}?",
    hint: "ey ท้ายคำบางทีออก 'อี'", spellWord: "key", spellAnswer: "ey" },
  { id: "ie-ee", group: "long-e", display: "ie", ipa: "/iː/", thai: "อี",
    examples: ["field", "chief", "believe"], sentence: "Run on the {field}.",
    hint: "ie หลายคำออก 'อี' (จำ: i ก่อน e)", spellWord: "field", spellAnswer: "ie" },

  // ══════════ หมวด 4: เสียง โอ /oʊ/ ══════════
  { id: "oa", group: "long-o", display: "oa", ipa: "/oʊ/", thai: "โอ",
    examples: ["boat", "road", "coat"], sentence: "A {boat} on the river.",
    hint: "oa ออก 'โอ'", spellWord: "boat", spellAnswer: "oa" },
  { id: "ow-o", group: "long-o", display: "ow", ipa: "/oʊ/", thai: "โอ",
    examples: ["snow", "low", "grow"], sentence: "The {snow} is white.",
    hint: "ow บางคำออก 'โอ' เช่น snow", spellWord: "snow", spellAnswer: "ow" },
  { id: "oe", group: "long-o", display: "oe", ipa: "/oʊ/", thai: "โอ",
    examples: ["toe", "goes", "hoe"], sentence: "I hurt my {toe}.",
    hint: "oe ท้ายคำมักออก 'โอ'", spellWord: "toe", spellAnswer: "oe" },

  // ══════════ หมวด 5: เสียง อู / ยู / อุ ══════════
  { id: "oo-long", group: "long-u", display: "oo", ipa: "/uː/", thai: "อู",
    examples: ["moon", "food", "soon"], sentence: "The {moon} is bright.",
    hint: "oo เสียงยาว 'อู'", spellWord: "moon", spellAnswer: "oo" },
  { id: "oo-short", group: "long-u", display: "oo", ipa: "/ʊ/", thai: "อุ",
    examples: ["book", "good", "look"], sentence: "Read a {book}.",
    hint: "oo เสียงสั้น 'อุ'", spellWord: "book", spellAnswer: "oo" },
  { id: "ew", group: "long-u", display: "ew", ipa: "/uː/", thai: "อู",
    examples: ["new", "few", "grew"], sentence: "I want a {new} one.",
    hint: "ew ออก 'อู' (บางคำ 'ยู' เช่น few)", spellWord: "new", spellAnswer: "ew" },
  { id: "ue", group: "long-u", display: "ue", ipa: "/uː/", thai: "อู",
    examples: ["blue", "true", "glue"], sentence: "The sky is {blue}.",
    hint: "ue ออก 'อู' (บางคำ 'ยู' เช่น cue)", spellWord: "blue", spellAnswer: "ue" },
  { id: "ui", group: "long-u", display: "ui", ipa: "/uː/", thai: "อู",
    examples: ["fruit", "juice", "suit"], sentence: "I like {fruit}.",
    hint: "ui ออก 'อู'", spellWord: "fruit", spellAnswer: "ui" },

  // ══════════ หมวด 6: สระประสม (ไอ · ออย · เอา) ══════════
  { id: "igh", group: "diphthong", display: "igh", ipa: "/aɪ/", thai: "ไอ",
    examples: ["high", "light", "night"], sentence: "A {light} at night.",
    hint: "igh ออก 'อาย' (gh เงียบ)", spellWord: "light", spellAnswer: "igh" },
  { id: "ie-ai", group: "diphthong", display: "ie", ipa: "/aɪ/", thai: "ไอ",
    examples: ["pie", "tie", "lie"], sentence: "I eat a {pie}.",
    hint: "ie ท้ายคำสั้น ๆ มักออก 'อาย'", spellWord: "pie", spellAnswer: "ie" },
  { id: "oi", group: "diphthong", display: "oi", ipa: "/ɔɪ/", thai: "ออย",
    examples: ["coin", "boil", "voice"], sentence: "I drop a {coin}.",
    hint: "oi ออก 'ออย' (มักกลางคำ)", spellWord: "coin", spellAnswer: "oi" },
  { id: "oy", group: "diphthong", display: "oy", ipa: "/ɔɪ/", thai: "ออย",
    examples: ["boy", "toy", "joy"], sentence: "The {boy} has a toy.",
    hint: "oy ออก 'ออย' (มักท้ายคำ)", spellWord: "boy", spellAnswer: "oy" },
  { id: "ow-au", group: "diphthong", display: "ow", ipa: "/aʊ/", thai: "เอา",
    examples: ["now", "cow", "how"], sentence: "The {cow} is here.",
    hint: "ow บางคำออก 'เอา' เช่น now, cow", spellWord: "cow", spellAnswer: "ow" },
  { id: "ou", group: "diphthong", display: "ou", ipa: "/aʊ/", thai: "เอา",
    examples: ["house", "mouse", "out"], sentence: "A {mouse} in the house.",
    hint: "ou ออก 'เอา' (มีหลายเสียง: soup, touch)", spellWord: "house", spellAnswer: "ou" },

  // ══════════ หมวด 7: เสียง ออ /ɔː/ (au · aw · augh) ══════════
  { id: "au", group: "broad-o", display: "au", ipa: "/ɔː/", thai: "ออ",
    examples: ["sauce", "August", "author"], sentence: "Add the {sauce}.",
    hint: "au ออก 'ออ'", spellWord: "sauce", spellAnswer: "au" },
  { id: "aw", group: "broad-o", display: "aw", ipa: "/ɔː/", thai: "ออ",
    examples: ["saw", "draw", "law"], sentence: "I {saw} a dog.",
    hint: "aw ออก 'ออ' (มักท้ายคำ)", spellWord: "saw", spellAnswer: "aw" },
  { id: "augh", group: "broad-o", display: "augh", ipa: "/ɔː/", thai: "ออ",
    examples: ["caught", "taught", "daughter"], sentence: "I {caught} the ball.",
    hint: "augh ออก 'ออ' (gh เงียบ)", spellWord: "caught", spellAnswer: "augh" },

  // ══════════ หมวด 8: สระ + R พื้นฐาน ══════════
  { id: "ar", group: "r-basic", display: "ar", ipa: "/ɑː/", thai: "อา",
    examples: ["car", "far", "star"], sentence: "The {car} is far.",
    hint: "ar ออก 'อาร์'", spellWord: "car", spellAnswer: "ar" },
  { id: "or", group: "r-basic", display: "or", ipa: "/ɔː/", thai: "ออ",
    examples: ["corn", "born", "fork"], sentence: "I eat {corn}.",
    hint: "or ออก 'ออร์'", spellWord: "corn", spellAnswer: "or" },
  { id: "er", group: "r-basic", display: "er", ipa: "/ɜː/", thai: "เออ",
    examples: ["her", "term", "person"], sentence: "I see {her}.",
    hint: "er ออก 'เออร์'", spellWord: "her", spellAnswer: "er" },
  { id: "ir", group: "r-basic", display: "ir", ipa: "/ɜː/", thai: "เออ",
    examples: ["bird", "girl", "first"], sentence: "The {bird} sings.",
    hint: "ir ออก 'เออร์'", spellWord: "bird", spellAnswer: "ir" },
  { id: "ur", group: "r-basic", display: "ur", ipa: "/ɜː/", thai: "เออ",
    examples: ["turn", "burn", "nurse"], sentence: "It's my {turn}.",
    hint: "ur ออก 'เออร์'", spellWord: "turn", spellAnswer: "ur" },

  // ══════════ หมวด 9: สระ + R พิเศษ (แอร์ · เอีย · ออร์) ══════════
  { id: "air", group: "r-extra", display: "air", ipa: "/eə/", thai: "แอร์",
    examples: ["hair", "chair", "fair"], sentence: "Sit on the {chair}.",
    hint: "air ออก 'แอร์'", spellWord: "chair", spellAnswer: "air" },
  { id: "are", group: "r-extra", display: "are", ipa: "/eə/", thai: "แอร์",
    examples: ["care", "share", "bare"], sentence: "I {care} about you.",
    hint: "are ออก 'แอร์' เหมือน air", spellWord: "care", spellAnswer: "are" },
  { id: "ear", group: "r-extra", display: "ear", ipa: "/ɪə/", thai: "เอีย",
    examples: ["hear", "ear", "year"], sentence: "I can {hear} you.",
    hint: "ear มักออก 'เอีย' (บางคำต่าง: earth, bear)", spellWord: "hear", spellAnswer: "ear" },
  { id: "eer", group: "r-extra", display: "eer", ipa: "/ɪə/", thai: "เอีย",
    examples: ["deer", "beer", "cheer"], sentence: "I see a {deer}.",
    hint: "eer ออก 'เอีย'", spellWord: "deer", spellAnswer: "eer" },
  { id: "ore", group: "r-extra", display: "ore", ipa: "/ɔː/", thai: "ออ",
    examples: ["more", "store", "score"], sentence: "I want {more}.",
    hint: "ore ออก 'ออร์'", spellWord: "more", spellAnswer: "ore" },
  { id: "our", group: "r-extra", display: "our", ipa: "/ɔː/", thai: "ออ",
    examples: ["four", "your", "pour"], sentence: "I have {four} cats.",
    hint: "our บางคำออก 'ออร์' เช่น four, your", spellWord: "four", spellAnswer: "our" },
];

// ป้ายชื่อหมวดสำหรับหน้าจอเลือก (เรียงตามลำดับที่อยากให้แสดง)
// title = ชื่อหมวด, ex = ตัวอย่างสระในหมวด
const GROUP_LABELS = {
  "magic-e":   { title: "Magic e",        ex: "a_e · i_e · o_e · u_e · e_e" },
  "long-a":    { title: "เสียง เอ",        ex: "ai · ay · ey · eigh · ei" },
  "long-e":    { title: "เสียง อี",        ex: "ee · ea · ey · ie" },
  "long-o":    { title: "เสียง โอ",        ex: "oa · ow · oe" },
  "long-u":    { title: "เสียง อู / ยู",   ex: "oo · ew · ue · ui" },
  "diphthong": { title: "สระประสม",       ex: "igh · ie · oi · oy · ow · ou" },
  "broad-o":   { title: "เสียง ออ",        ex: "au · aw · augh" },
  "r-basic":   { title: "สระ + R",        ex: "ar · or · er · ir · ur" },
  "r-extra":   { title: "สระ + R พิเศษ",   ex: "air · are · ear · eer · ore · our" },
};
